<?php

namespace CupCake\StockBundle\Repository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{

    function getsotck($idPat)
    {
        $query=$this->createQueryBuilder('p')
            ->where("idProduit.id like :s")
            ->setParameter("s",$idPat.'%');
        return $query->getQuery()->getResult();


    }

    public function ajouterstockform($idPat)
{
    $query=$this->getEntityManager()->createQuery(
        "select p from ProduitBundle:Produit p JOIN CupCakeStockBundle:Stock s where (p.id_produit <> s.idProduit
AND p.patisserie = s.idPatisserie) AND p.patisserie=:idPat")
            ->setParameter('idPat',$idPat);
    return $query->getResult();
}
    public function recupererID($libelleProduit)
{
    $query=$this->getEntityManager()->createQuery(
        "select p.idProduit from ProduitBundle:Produit p  where p.libelleProduit =:libelleProduit")
        ->setParameter('libelleProduit',$libelleProduit);
    return $query->getResult();
}




}
