<?php

namespace CupCake\ProduitBundle\Repository;


/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    function getProduitByPatisserie1($idPat)
    {

        $query=$this->getEntityManager()->createQuery(
            "select p from ProduitBundle:Produit p JOIN CupCakeStockBundle:Stock s where p.id_produit = s.idProduit AND p.patisserie=:idPat")
            ->setParameter('idPat',$idPat);
        return $query->getResult();

    }

    public function recupererID($libelleProduit)
    {
        $query=$this->getEntityManager()->createQuery(
            "select p from ProduitBundle:Produit p  where p.libelleProduit =:libelleProduit")
            ->setParameter('libelleProduit',$libelleProduit);
        return $query->getResult();
    }

}
